/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAggregator__factory } from "./IAggregator__factory";
export { IFeedRegistry__factory } from "./IFeedRegistry__factory";
