/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainLink from "./ChainLink";
export type { chainLink };
import type * as uniswap from "./Uniswap";
export type { uniswap };
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IMulticall3 } from "./IMulticall3";
export type { ISTETH } from "./ISTETH";
export type { IWETH } from "./IWETH";
export type { IWSTETH } from "./IWSTETH";
